# Generated by Django 2.0 on 2019-10-23 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_name', models.CharField(max_length=255, verbose_name='用户姓名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (0, '女')], verbose_name='用户性别')),
                ('job_number', models.IntegerField(verbose_name='工号')),
                ('tel', models.IntegerField(verbose_name='电话')),
                ('address1', models.CharField(max_length=255, verbose_name='1级收货地址')),
                ('address2', models.CharField(max_length=255, verbose_name='2级收货地址')),
                ('describe', models.CharField(max_length=255, verbose_name='描述')),
                ('picture', models.ImageField(upload_to='uploads/user/%Y/', verbose_name='用户头像')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
