# Generated by Django 2.0 on 2019-10-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/user/%Y/', verbose_name='用户头像'),
        ),
    ]
