# Generated by Django 2.0 on 2019-10-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191024_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address1',
            field=models.CharField(max_length=255, verbose_name='1级家庭地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address2',
            field=models.CharField(max_length=255, verbose_name='2级家庭地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job_number',
            field=models.CharField(max_length=255, verbose_name='工号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(max_length=255, verbose_name='电话'),
        ),
    ]
