# Generated by Django 2.0 on 2019-10-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191024_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='login_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近登录时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '冻结'), (1, '活跃')], null=True, verbose_name='角色'),
        ),
    ]
