# Generated by Django 2.0 on 2019-10-24 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20191023_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorapprove',
            name='door_addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 19, 18, 14, 163190), verbose_name='申请添加时间'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='log_addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 19, 18, 14, 164188), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 19, 18, 14, 163190), verbose_name='添加时间'),
        ),
    ]
