# Generated by Django 2.0 on 2019-10-25 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20191025_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorapprove',
            name='door_addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 25, 15, 36, 35, 542449), verbose_name='申请添加时间'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='log_addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 25, 15, 36, 35, 542449), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 25, 15, 36, 35, 542449), verbose_name='添加时间'),
        ),
    ]
