# Generated by Django 2.0 on 2019-10-25 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alarm_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('am_addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='告警时间')),
                ('am_type_id', models.IntegerField(verbose_name='告警类型')),
                ('am_level_id', models.IntegerField(verbose_name='告警等级')),
                ('scene_id', models.IntegerField(verbose_name='告警场景id')),
                ('am_device', models.CharField(max_length=255, verbose_name='告警设备')),
                ('am_content', models.CharField(max_length=255, verbose_name='告警内容')),
                ('am_status', models.IntegerField(verbose_name='告警状态')),
                ('am_deal_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='告警处理人')),
                ('am_deal_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('am_deal_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='告警处理说明')),
                ('am_audit_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='告警审核人')),
                ('am_audit_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('am_audit_feedback', models.CharField(blank=True, max_length=255, null=True, verbose_name='审核反馈')),
            ],
        ),
    ]
