# Generated by Django 2.0 on 2019-10-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alarm_management',
            new_name='AlarmManagement',
        ),
    ]
