# Generated by Django 2.0 on 2019-10-29 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0004_auto_20191029_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_addtime', models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 979932), verbose_name='场景添加时间')),
                ('scene_name', models.CharField(max_length=255, verbose_name='场景名称')),
                ('scene_code', models.CharField(max_length=255, verbose_name='场景识别码')),
                ('scene_gatewaypwd', models.CharField(max_length=255, verbose_name='网关密码')),
                ('scene_status', models.IntegerField(choices=[(1, '在线'), (2, '离线')], default=2, verbose_name='场景状态')),
                ('scene_level', models.IntegerField(verbose_name='场景优先级')),
            ],
        ),
        migrations.AlterField(
            model_name='alarmlamp',
            name='alarmlamp_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 977938), verbose_name='报警灯更新时间'),
        ),
        migrations.AlterField(
            model_name='alertor',
            name='alertor_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 978935), verbose_name='报警器更新时间'),
        ),
        migrations.AlterField(
            model_name='beam',
            name='beam_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 976940), verbose_name='光照更新时间'),
        ),
        migrations.AlterField(
            model_name='co2',
            name='co2_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 976940), verbose_name='co2更新时间'),
        ),
        migrations.AlterField(
            model_name='display',
            name='display_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 978935), verbose_name='显示内容更新时间'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='fan_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 978935), verbose_name='风扇更新时间'),
        ),
        migrations.AlterField(
            model_name='flame',
            name='flame_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 977938), verbose_name='火光更新时间'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='humidity_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 976940), verbose_name='湿度更新时间'),
        ),
        migrations.AlterField(
            model_name='invade',
            name='invade_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 979932), verbose_name='入侵检测更新时间'),
        ),
        migrations.AlterField(
            model_name='light',
            name='light_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 978935), verbose_name='灯光数据更新时间'),
        ),
        migrations.AlterField(
            model_name='methane',
            name='methane_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 977938), verbose_name='甲烷更新时间'),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='pm25_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 977938), verbose_name='pm25更新时间'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='pump_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 978935), verbose_name='水泵更新时间'),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='smoke_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 977938), verbose_name='烟雾更新时间'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 53, 30, 976940), verbose_name='温度更新时间'),
        ),
    ]
