# Generated by Django 2.0 on 2019-10-29 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0005_auto_20191029_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarmlamp',
            options={'verbose_name': '报警灯'},
        ),
        migrations.AlterModelOptions(
            name='alertor',
            options={'verbose_name': '报警器'},
        ),
        migrations.AlterModelOptions(
            name='beam',
            options={'verbose_name': '光照强度传感器'},
        ),
        migrations.AlterModelOptions(
            name='co2',
            options={'verbose_name': '二氧化碳传感器'},
        ),
        migrations.AlterModelOptions(
            name='display',
            options={'verbose_name': 'LCD显示器'},
        ),
        migrations.AlterModelOptions(
            name='fan',
            options={'verbose_name': '风扇传感器'},
        ),
        migrations.AlterModelOptions(
            name='flame',
            options={'verbose_name': '火光传感器'},
        ),
        migrations.AlterModelOptions(
            name='humidity',
            options={'verbose_name': '湿度传感器'},
        ),
        migrations.AlterModelOptions(
            name='invade',
            options={'verbose_name': '入侵检测'},
        ),
        migrations.AlterModelOptions(
            name='light',
            options={'verbose_name': '灯光传感器'},
        ),
        migrations.AlterModelOptions(
            name='methane',
            options={'verbose_name': '甲烷传感器'},
        ),
        migrations.AlterModelOptions(
            name='pm25',
            options={'verbose_name': 'PM2.5传感器'},
        ),
        migrations.AlterModelOptions(
            name='pump',
            options={'verbose_name': '水泵传感器'},
        ),
        migrations.AlterModelOptions(
            name='smoke',
            options={'verbose_name': '烟雾传感器'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'verbose_name': '温度传感器'},
        ),
        migrations.AlterModelOptions(
            name='unlocking',
            options={'verbose_name': '开锁记录表'},
        ),
        migrations.AlterField(
            model_name='alarmlamp',
            name='alarmlamp_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 38, 998623), verbose_name='报警灯更新时间'),
        ),
        migrations.AlterField(
            model_name='alertor',
            name='alertor_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 38, 998623), verbose_name='报警器更新时间'),
        ),
        migrations.AlterField(
            model_name='beam',
            name='beam_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 38, 996592), verbose_name='光照更新时间'),
        ),
        migrations.AlterField(
            model_name='co2',
            name='co2_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 38, 997590), verbose_name='co2更新时间'),
        ),
        migrations.AlterField(
            model_name='display',
            name='display_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 38, 998623), verbose_name='显示内容更新时间'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='fan_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 38, 999610), verbose_name='风扇更新时间'),
        ),
        migrations.AlterField(
            model_name='flame',
            name='flame_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 38, 997590), verbose_name='火光更新时间'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='humidity_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 38, 996592), verbose_name='湿度更新时间'),
        ),
        migrations.AlterField(
            model_name='invade',
            name='invade_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 39, 624), verbose_name='入侵检测更新时间'),
        ),
        migrations.AlterField(
            model_name='light',
            name='light_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 38, 999610), verbose_name='灯光数据更新时间'),
        ),
        migrations.AlterField(
            model_name='methane',
            name='methane_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 38, 998623), verbose_name='甲烷更新时间'),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='pm25_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 38, 997590), verbose_name='pm25更新时间'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='pump_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 38, 999610), verbose_name='水泵更新时间'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='scene_addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 39, 624), verbose_name='场景添加时间'),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='smoke_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 38, 997590), verbose_name='烟雾更新时间'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 14, 42, 38, 996592), verbose_name='温度更新时间'),
        ),
    ]
