# Generated by Django 2.0 on 2019-10-29 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0007_auto_20191029_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='co2',
            name='co2_name',
            field=models.CharField(default='CO2传感器', max_length=255),
        ),
        migrations.AddField(
            model_name='invade',
            name='invade_name',
            field=models.CharField(default='门禁', max_length=255),
        ),
        migrations.AddField(
            model_name='methane',
            name='methane_name',
            field=models.CharField(default='甲烷传感器', max_length=255),
        ),
        migrations.AddField(
            model_name='pm25',
            name='pm25_name',
            field=models.CharField(default='PM2.5传感器', max_length=255),
        ),
        migrations.AddField(
            model_name='temperature',
            name='temperature_name',
            field=models.CharField(default='温度传感器', max_length=255),
        ),
        migrations.AlterField(
            model_name='alarmlamp',
            name='alarmlamp_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 565439), verbose_name='报警灯更新时间'),
        ),
        migrations.AlterField(
            model_name='alertor',
            name='alertor_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 565439), verbose_name='报警器更新时间'),
        ),
        migrations.AlterField(
            model_name='beam',
            name='beam_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 564442), verbose_name='光照更新时间'),
        ),
        migrations.AlterField(
            model_name='co2',
            name='co2_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 564442), verbose_name='co2更新时间'),
        ),
        migrations.AlterField(
            model_name='display',
            name='display_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 566436), verbose_name='显示内容更新时间'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='fan_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 566436), verbose_name='风扇更新时间'),
        ),
        migrations.AlterField(
            model_name='flame',
            name='flame_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 565439), verbose_name='火光更新时间'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='humidity_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 563408), verbose_name='湿度更新时间'),
        ),
        migrations.AlterField(
            model_name='invade',
            name='invade_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 567434), verbose_name='入侵检测更新时间'),
        ),
        migrations.AlterField(
            model_name='light',
            name='light_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 566436), verbose_name='灯光数据更新时间'),
        ),
        migrations.AlterField(
            model_name='methane',
            name='methane_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 565439), verbose_name='甲烷更新时间'),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='pm25_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 564442), verbose_name='pm25更新时间'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='pump_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 566436), verbose_name='水泵更新时间'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='scene_addtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 567434), verbose_name='场景添加时间'),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='smoke_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 564442), verbose_name='烟雾更新时间'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 15, 52, 27, 563408), verbose_name='温度更新时间'),
        ),
    ]
